import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import App from "@/components/app";
import { DefaultSeo } from 'next-seo';

 

export const metadata: Metadata = {
  title: "Lumey Energy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
          <App>{children}</App>
        
  );
}
