import type { Metadata } from "next";
import "./globals.css";
import App from "@/components/app";

export const metadata: Metadata = {
  title: "Lumey Energy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <App>{children}</App>;
}
