"use client";
import { FloatingCTA, Footer, Header } from "@/components";
import { AuthProvider } from "@/context/AuthContext";
import { DefaultSeo } from "next-seo";
import { usePathname } from "next/navigation";
import { ReactNode } from "react";



const App = ({ children }: { children: ReactNode }) => {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <DefaultSeo
          title="Lumey Energy"
          description="Generated by create next app"
          openGraph={{
            type: 'website',
            locale: 'en_US',
            url: 'https://lumey-energy.com',
            site_name: 'Lumey Energy',
          }}
          twitter={{
            handle: '@lumeyenergy',
            site: '@lumeyenergy',
            cardType: 'summary_large_image',
          }}
        />
      </head>
      <body
        className={` antialiased`}
      >
        <AuthProvider>
        <div>
        {pathname.includes("api-doc") || pathname.includes("admin") ? (
          <div>{children}</div>
        ) : (
          <div>
            <Header />
            <div>{children}</div>
            <Footer />
            <FloatingCTA />
          </div>
        )}
      </div>
        </AuthProvider>
      </body>
    </html>
  );
};

export default App;
